import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { faker } from '@faker-js/faker';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by {' '}
          <code className={styles.code}>routing</code>
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <Link href="/static" className={styles.card}>
              <h2>정적 라우팅 &rarr;</h2>
              <p>/pages 하위 디렉토리의 정적인 위치에 있는 정적 페이지로 이동</p>
            </Link>
          </div>
          <div className={styles.card}> 
            <Link href={`/user/${faker.name.firstName()}`}>
              <h2>동적 라우팅 &rarr;</h2>
              <p>faker 라이브러리를 이용하여 랜덤한 동적 페이지로 이동</p>
            </Link>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
